import {describe,it,expect} from 'vitest';
import worker from '../src/index';
const env={PUBLIC_ORIGIN:'https://dealhound.example',SOURCE_AUTHORIZED:'false',FEED_URL:'https://source.example/rss',FEED_NAME:'Source',FEED_COUNTRY:'US',FEED_CURRENCY:'USD',RATE_LIMITER:{limit:async()=>({success:true})} as RateLimit,ASSETS:{fetch:async()=>new Response('asset')} as unknown as Fetcher};
const ctx={waitUntil:()=>{}} as unknown as ExecutionContext;
const request=()=>new Request(env.PUBLIC_ORIGIN+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})});
describe('public worker boundary',()=>{
 it('serves MCP anonymously and publishes no OAuth metadata',async()=>{const response=await worker.fetch(request(),env,ctx);expect(response.status).toBe(200);expect(response.headers.has('WWW-Authenticate')).toBe(false);expect(JSON.stringify(await response.json())).toContain('noauth');expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/.well-known/oauth-protected-resource'),env,ctx)).status).toBe(404);});
 it('rejects host/origin abuse, oversize requests and invalid methods',async()=>{expect((await worker.fetch(new Request('https://other.example/mcp'),env,ctx)).status).toBe(403);expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/mcp',{headers:{Origin:'https://evil.example'}}),env,ctx)).status).toBe(403);expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/mcp',{method:'POST',headers:{'Content-Length':'70000'}}),env,ctx)).status).toBe(413);expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/mcp',{method:'PUT'}),env,ctx)).status).toBe(405);});
 it('fails closed for placeholder configuration and disabled source readiness',async()=>{expect((await worker.fetch(request(),{...env,PUBLIC_ORIGIN:'https://REPLACE.workers.dev'},ctx)).status).toBe(503);expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/ready'),env,ctx)).status).toBe(503);expect((await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/ready'),{...env,SOURCE_AUTHORIZED:'true'},ctx)).status).toBe(200);});
 it('bounds anonymous traffic without storing individual identifiers',async()=>{const res=await worker.fetch(request(),{...env,RATE_LIMITER:{limit:async()=>({success:false})} as RateLimit},ctx);expect(res.status).toBe(429);expect(res.headers.get('Retry-After')).toBe('60');});
 it('serves domain challenge as exact plain text only when configured',async()=>{const url=env.PUBLIC_ORIGIN+'/.well-known/openai-apps-challenge';expect((await worker.fetch(new Request(url),env,ctx)).status).toBe(404);expect(await (await worker.fetch(new Request(url),{...env,OPENAI_CHALLENGE:'verification-test'},ctx)).text()).toBe('verification-test');});
});
